/*
 * This source file was generated by the Gradle 'init' task
 */
package bitcamp.project3;

import bitcamp.menu.MenuGroup;
import bitcamp.menu.MenuItem;
import bitcamp.project3.command.Borrow.*;
import bitcamp.project3.command.Management.*;
import bitcamp.project3.command.NoticeCommand;
import bitcamp.project3.vo.Book;
import bitcamp.util.Prompt;

import java.util.List;


public class App {

  MenuGroup mainMenu = new MenuGroup("메인");

  NoticeCommand noticeCommand;

  public App() {
    //    List<Book> bookList = new ArrayList<>();
    List<Book> bookList = DummyData.createDummyBooks();

    noticeCommand = new NoticeCommand();

    MenuGroup bookMenu = new MenuGroup("도서 관리");
    ManagementShowListCommand showListCommand = new ManagementShowListCommand(bookList);
    bookMenu.add(new MenuItem("도서 등록", new ManagementAddCommand(bookList)));
    bookMenu.add(new MenuItem("도서 목록", new ManagementListCommand(bookList)));
    bookMenu.add(new MenuItem("도서 조회", new ManagementViewCommand(bookList)));
    bookMenu.add(new MenuItem("도서 변경", new ManagementUpdateCommand(bookList, showListCommand)));
    bookMenu.add(new MenuItem("도서 삭제", new ManagementDeleteCommand(bookList, showListCommand)));
    mainMenu.add(bookMenu);

    MenuGroup borrowMenu = new MenuGroup("대출 관리");
    BorrowBookHandler bookHandler = new BorrowBookHandler(bookList);
    borrowMenu.add(new MenuItem("도서 대출", new BorrowBorrowCommand(bookList, bookHandler)));
    borrowMenu.add(new MenuItem("대출 목록", new BorrowListCommand(bookList)));
    borrowMenu.add(new MenuItem("도서 반납 ", new BorrowReturnCommand(bookList, bookHandler)));
    borrowMenu.add(new MenuItem("대출 연장", new BorrowExtendCommand(bookList, bookHandler)));
    borrowMenu.add(new MenuItem("연체 내역", new BorrowListOverCommand(bookList)));
    mainMenu.add(borrowMenu);

    mainMenu.add(new MenuItem("공지 사항", noticeCommand));

    mainMenu.setExitMenuTitle("종료");
  }

  public static void main(String[] args) {
    new App().execute();
  }

  void execute() {
    String boldAnsi = "\033[1m";
    String resetAnsi = "\033[0m";

    String appTitle = "[도서 관리 프로그램]";
    String line = "----------------------------------";

    System.out.println(boldAnsi + line + resetAnsi);
    System.out.println(boldAnsi + appTitle + resetAnsi);
    
    try {
      mainMenu.execute();
    } catch (Exception ex) {
      System.out.println("실행 오류!");
    }

    System.out.println("종료합니다.");

    Prompt.close();
  }
}
